[package]
name = "pongrs"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
error-iter = "0.4.1"
log = "0.4.27"
pixels = "0.15.0"
winit = "0.29.1"
winit_input_helper = "0.16.0"
